moviesproject/moviesapp/urls.py
from django.conf.urls import url
from moviesapp import views

# Template Tagging

app_name = 'moviesapp'

urlpatterns = [
    url(r'^movies/$',views.movies,name='movies'),
    #url(r'^register/$',views.register,name='register'),
    #url(r'^login/$',views.login_view,name='login'),
    url(r'^add/$',views.add_movie_view,name='add'),

]

moviesproject/moviesproject/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from moviesapp import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^moviesapp/',include('moviesapp.urls')),
    url(r'^login/$',views.login_view,name='login'),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^register/$',views.register,name='register'),
]

moviesproject/moviesapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Genre (models.Model):
    name = models.CharField(max_length=128,unique=True)

    def __str__(self):
        return str(self.name)


class Movie (models.Model):
    title = models.CharField(max_length=128,unique=True)
    year = models.IntegerField()
    runtime = models.IntegerField()
    genres = models.ManyToManyField(Genre)
    votes = models.IntegerField()
    rate = models.FloatField(max_length=4)
    desc = models.CharField(max_length=256,verbose_name='Description',)
    dateadded = models.DateField(default=timezone.now,verbose_name='Date Added')

    def __str__(self):
        return str(self.title + ' ' + str(self.year))


class UserProfileInfo(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )

    user = models.OneToOneField(User)

    #additional field
    profile_pic = models.ImageField(upload_to='profile_pics',verbose_name='Profile Picture',blank=True)
    wechat = models.CharField(max_length=128,unique=True,verbose_name='WeChat',blank=True)
    qq = models.IntegerField(unique=True,verbose_name='QQ',blank=True)
    mobile = models.CharField(max_length=15,unique=True,blank=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)

    def __str__(self):
        return self.user.username

moviesproject/moviesapp/forms.py
from django import forms
from django.contrib.auth.models import User
from moviesapp.models import UserProfileInfo, Genre, Movie

# class MovieForm(forms.Form):
#     title = models.CharField(max_length=128,unique=True)
#     year =  models.IntegerField(max_length=4)
#     runtime = models.IntegerField(max_length=4)
#     #genres = models.ForeignKey(Genre)
#     votes = models.IntegerField()
#     rate = models.FloatField(max_length=4)
#     desc = models.CharField(widget=forms.Textarea)
#     dateadded = models.DateField(default=timezone.now)

class NewMovieForm(forms.ModelForm):
    class Meta():
        model = Movie
        fields = ('title','year', 'runtime', 'genres','votes', 'rate', 'desc','dateadded')

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('profile_pic','wechat', 'qq', 'mobile','gender')

moviesproject/moviesapp/views.py
from django.shortcuts import render
from moviesapp.models import Genre, Movie
from moviesapp.forms import UserForm, UserProfileInfoForm, NewMovieForm
#pagenation
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

#
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.

def index(request):

    # genres = Genre.objects.order_by('name')
    # moveis = Movie.objects.order_by('year')
    #
    # data_dict = {'genres':genres,'moveis':moveis}
    #return render(request,'moviesapp/index.html',context=data_dict)
    return render(request,'moviesapp/index.html')

def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'moviesapp/registration.html',
                            {'user_form':user_form,
                             'profile_form': profile_form,
                             'registered':registered})
@login_required(login_url='/login/')
def add_movie_view(request):

    if request.method == 'POST':
        add_movie_form = NewMovieForm(data=request.POST)

        if add_movie_form.is_valid():
            movie = add_movie_form.save(commit=False)


            movie.save()
        else:
            print(add_movie_form.errors)

    else:
        add_movie_form = NewMovieForm()

    return render(request,'moviesapp/add.html',
                            {'add_movie_form':add_movie_form})
#@login_required(login_url='/login/')
def movies(request):
    movies_list = Movie.objects.all()
    genres = Genre.objects.order_by('name')

    paginator = Paginator(movies_list, 25) # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        movies = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        movies = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        movies = paginator.page(paginator.num_pages)

    data_dict = {'movies':movies,'genres':genres}

    return render(request,'moviesapp/movies.html',context=data_dict)

def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account not active')
        else:
            print('someone tried to login and failed.')
            print('Username: {0} and password {1}'.format(username,password))
            return HttpResponse('invalid login details supplied.')

    return render(request,'moviesapp/login.html',{})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

moviesproject/templates/moviesapp/add.html
{% extends 'moviesapp/base.html' %}
{% load staticfiles %}
{% load bootstrap %}

{% block body_block%}

<div class="">
  {% if user.is_authenticated and user.is_superuser %}

    <div class="row">
      <div class="col-xs-1 col-md-3"></div>
      <div class="col-xs-10 col-md-6">
        <h3>Add a new movie here!</h3>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ add_movie_form|bootstrap}}
          <input type="submit" class="btn btn-primary" value="Add">
        </form>
      </div>
      <div class="col-xs-1 col-md-3"></div>
    </div>
  {% else %}
    <h3 class="text-center">Please login first</h3>
  {% endif %}
</div>

{% endblock %}

moviesproject/templates/moviesapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap-paper.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
    <link rel="icon" href="{% static 'images/icon.ico' %}">
    <title>X-Movies</title>
  </head>
  <body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
       <div class="container">
         <div class="navbar-header">
           <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
             <span class="sr-only">Toggle navigation</span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
           </button>
           <a class="navbar-brand" href="/">X-Movies</a>
         </div>
         <div id="navbar" class="collapse navbar-collapse">
           <ul class="nav navbar-nav">
             <li><a href="/">Home</a></li>
             <li><a href="{% url 'moviesapp:movies' %}">Movies</a></li>
           </ul>

           <ul class="nav navbar-nav navbar-right">
             {% if user.is_authenticated %}
              {% if user.is_superuser %}
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
                <li><a href="{% url 'moviesapp:add' %}">Add</a></li>
              {% endif %}
              <li><a href="{% url 'logout' %}">Logout</a></li>
             {% else %}
            <li><a href="{% url 'login' %}">Login</a></li>
            <li><a href="{% url 'register' %}">Register</a></li>
             {% endif %}
          </ul>
         </div><!--/.nav-collapse -->
       </div>
     </nav>

    <div class="container">
      {% block body_block %}
      {% endblock%}
    </div>

    <!-- Bootstrap core JavaScript
   ================================================== -->
   <!-- Placed at the end of the document so the pages load faster -->
   <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
   <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

moviesproject/templates/moviesapp/index.html
{% extends 'moviesapp/base.html' %}
{% block body_block%}

<div class="jumbotron">
  <h1>X-Movies</h1>
  <p>welcome to X-Movies</p>
</div>

{% endblock %}

moviesproject/templates/moviesapp/login.html
{% extends 'moviesapp/base.html' %}
{% load staticfiles %}
{% load bootstrap %}

{% block body_block%}

<div class="">
  {% if user.is_authenticated %}
    <h3 class="text-center">You are already logged in</h3>
  {% else %}
    <h3 class="text-center">Please Login</h3>
    <div class="row">
      <div class="col-xs-1 col-md-3"></div>
      <div class="col-xs-10 col-md-6">
        <form action="{% url 'login' %}" method="POST">
          {% csrf_token %}
          <div class="form-group">
             <label class="control-label" for="username">Username:</label>
             <input type="text" name="username" class="form-control" placeholder="Enter Username">
         </div>
         <div class="form-group">
            <label class="control-label" for="password">Password:</label>
            <input type="password" name="password" class="form-control" >
        </div>



          <input type="submit" class="btn btn-primary" value="Login">
        </form>
      </div>
      <div class="col-xs-1 col-md-3"></div>
    </div>
  {% endif %}
</div>

{% endblock %}

moviesproject/templates/moviesapp/movies.html
{% extends 'moviesapp/base.html' %}
{% load staticfiles %}
{% block body_block%}
<br/>
<br/>



{% if movies %}

    {% for item in movies %}
      <div name='movie-list' class="row">
        <div class="media-left">
          <a href="http://www.imdb.com/search/title?title='{{item.title}}'" target="_blank">
            <img name='movie-image' class="media-object" style="width: 150px;" src="{% static 'images/icon.png' %}" alt="img">
          </a>
        </div>
        <div class="media-body">
          <h4 name='moive-title' class="media-heading">{{ item.title }} ({{ item.year }} )</h4>
          {% with item.rate|stringformat:"i" as rate %}
            {% if rate in "8" %}
              <p> <span class='text-success'><i class="fa fa-star" aria-hidden="true"></i> <b name='movie-rates' >{{ item.rate }}</b> </span> &emsp;|&emsp; <span name='movie-genres'>Genre: {% for genre in item.genres.all %}{{ genre }} {% endfor %}</span></p>
            {% else %}
              <p> <span class='text-warning'><i class="fa fa-star" aria-hidden="true"></i> <b>{{ item.rate }}</b> </span> &emsp;|&emsp; Genre: {% for genre in item.genres.all %}{{ genre }} {% endfor %}</p>
            {% endif %}
          {% endwith %}

          <p><i class="fa fa-thumbs-o-up" aria-hidden="true"></i> Votes: {{ item.votes }} &emsp;|&emsp; <i class="fa fa-hourglass" aria-hidden="true"></i> Runtime: {{ item.runtime }} min</p>
          <p>{{ item.desc }}</p>
        </div>
      </div>
     {% endfor %}

     <nav aria-label="Page navigation">
       <ul class="pagination">
         {% if movies.has_previous %}
           <li>
             <a href="?page={{ movies.previous_page_number }}" aria-label="Previous">
               <span aria-hidden="true">&laquo;</span>
             </a>
           </li>
         {% endif %}



          <li><a href="#"> {{ movies.number }} / {{ movies.paginator.num_pages }}</a></li>


         {% if movies.has_next %}
           <li>
            <a href="?page={{ movies.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        {% endif %}
      </ul>
    </nav>
{% else %}
 <p>No records!</p>
{% endif %}

{% endblock %}

moviesproject/templates/moviesapp/registration.html
{% extends 'moviesapp/base.html' %}
{% load staticfiles %}
{% load bootstrap %}

{% block body_block%}

<div class="">
  {% if registered %}
    <h3 class="text-center">Thank you for registrering!</h3>
  {% else %}
    <h3 class="text-center"><i class="fa fa-registered" aria-hidden="true"></i> Register here!</h3>
    <div class="row">
      <div class="col-xs-1 col-md-3"></div>
      <div class="col-xs-10 col-md-6">
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form|bootstrap}}
          {{ profile_form|bootstrap }}
          <input type="submit" class="btn btn-primary" value="Register">
        </form>
      </div>
      <div class="col-xs-1 col-md-3"></div>
    </div>
  {% endif %}
</div>

{% endblock %}